### ISSUE TITLE
Error when using findOne() in publication

### ISSUE THREAD

**Issue by Kymer** [johanbrook/meteor-publication-collector#1]
When using a `findOne()` query like so:

```
Meteor.publish('event', (id) => {
	return Events.findOne({_id: id})
})
```

I get an error when I try to call `collect()` on a publication collector:

```
Error: Object [object Object] has no method '_publishCursor'
    at packages/johanbrook:publication-collector/publication-collector.js:33:44
```

I realize `findOne()` doesn't return a cursor, but a document. For now I can use a regular `find()` query in the publication as a temporary workaround. Any suggestions on how to fix this issue?

**Comment by johanbrook** [comment]
Is it even allowed to return a non-cursor (when not calling `this.ready()`) in a subscription?

**Comment by Kymer** [comment]
Hmm good point. The [Meteor docs](http://docs.meteor.com/api/pubsub.html) do kind of state it should be either of 2 things:

1. A cursor
2. An array of cursors (of different collections)

>Publish functions can return a Collection.Cursor, in which case Meteor will publish that cursor’s documents to each subscribed client. You can also return an array of Collection.Cursors, in which case Meteor will publish all of the cursors.

It does not explicitly say it is forbidden, but perhaps it's best to avoid returning the result of a `findOne()` query then. I'll go ahead and close the issue :)

**Comment by johanbrook** [comment]
:) Yeah, `findOne` is returning a document (plain object), so I think it's kinda forbidden. Thanks anyway!
