### ISSUE TITLE
ES6 Error

### ISSUE THREAD

**Issue by aruntk** [johanbrook/meteor-publication-collector#14]
`this.userId` is `undefined` when using arrow function as argument of the publication.
```js
// pub.js
Meteor.publish('posts', function({ _id }) {
  const user = this.userId; // working correctly
  return Posts.find({ _id, user });
});
```
```js
// pub.js
Meteor.publish('posts', ({ _id }) => {
  const user = this.userId; // userId is undefined
  return Posts.find({ _id, user });
});
```
```js
// test.js
const collector = new PublicationCollector({ userId });
collector.collect('posts', (collections) => {
  assert.equal(collections.posts.length, 5);
  done();
});
```

**Comment by johanbrook** [comment]
Well, that's the behaviour of arrow functions, no? :) The arrow function's lexical scope in your second example will be bound to the outer, and makes `userId` be `undefined`.

**Comment by robsecord** [comment]
Correct. 
From MDN: 

> An arrow function expression [...] does not bind its own this, arguments, super, or new.target.
