### ISSUE TITLE
"ready" event sent twice for publications using the low-level added/changed/removed interface

### ISSUE THREAD

**Issue by nkahnfr** [johanbrook/meteor-publication-collector#16]
Hi,

First thanks for your package, it's really useful for testing Meteor publications.

With latest version I am getting following errors while testing my publications:
`Error: done() called multiple times`

Here the "done" function is the Mocha callback used for asynchronous code like the one you use in your usage example.

The publications I am testing are using the low-level added/changed/removed interface which means I am also calling the "ready" method once the initial record set is complete.
The problem in that case is that you're also calling ["this.ready()" at the end of "collect" method](https://github.com/johanbrook/meteor-publication-collector/blob/master/publication-collector.js#L53) and thus the callback passed to the "collect" method is called twice since it's part of [the "ready" listener you're defining before calling the publication function](https://github.com/johanbrook/meteor-publication-collector/blob/master/publication-collector.js#L32-L35).

That behavior was introduced in v1.0.5 since you're now adding the "ready" listener before calling the publication function.

I could be wrong but my recommendation would be to define an empty "ready" method on `PublicationCollector` class (like the `stop()` one) and use a different name for your custom ready event.

Let me know if that's not clear enough.
Thanks for your help.

-Nicolas

**Comment by johanbrook** [comment]
Hey there!

Thanks for reporting in. I see how you mean. I'll try to reproduce it as a failing test case.

**Comment by ShinyLeee** [comment]
@johanbrook Maybe you can see [this repro](https://github.com/ShinyLeee/meteor-publication-collector-repro).
#11

**Comment by nkahnfr** [comment]
@johanbrook I created pull request #18 to fix that issue. Hope it helps.

**Comment by johanbrook** [comment]
Thanks! Will check it out.

**Comment by johanbrook** [comment]
Published as 1.0.6.
