### ISSUE TITLE
eslint setup

### ISSUE THREAD

**Issue by lorensr** [johanbrook/meteor-publication-collector#26]
I did `npm i`, is there anything else I need to do to set up eslint? My editor (atom) is giving me `Error: Cannot find module 'eslint-config-lookback/meteor'`

**Comment by johanbrook** [comment]
Hm, I've seen this going away by referring to the embedded bin version of `eslint`:

```
./node_modules/.bin/esint .
```

**Comment by lorensr** [comment]
Worked, thanks!
