### ISSUE TITLE
Does this work with peerlibrary:reactive-publish

### ISSUE THREAD

**Issue by tpasque** [johanbrook/meteor-publication-collector#3]
?
This is what we get in our terminal as the error:

Exception in queued task: TypeError: Cannot call method 'idStringify' of undefined 
at PublicationCollector.publish.added (packages/peerlibrary_reactive-publish/packages/peerlibrary_reactive-publish.js:283:1) 
at added (packages/mongo/collection.js:346:11)
at packages/mongo/observe_multiplex.js:183:30
at Function._.each._.forEach (packages/underscore/underscore.js:108:1)
at Object.task (packages/mongo/observe_multiplex.js:177:9)
at [object Object]._.extend._run (packages/meteor/fiber_helpers.js:147:1)
at packages/meteor/fiber_helpers.js:125:1

**Comment by johanbrook** [comment]
Probably isn't working with that package, since it seems it somehow isn't providing `idStringify`. Can look into.

**Comment by iascchen** [comment]
I meet this issue alos. On meteor 1.4.0.1. And store all publications under folder like these: 

/imports/api/server/publications/books.publications.js 
/imports/api/server/publications/books.publications.test.js 

Exception in queued task: TypeError: Cannot read property 'idStringify' of undefined
I20160807-17:59:25.577(8)?     at PublicationCollector.publish.added (packages/peerlibrary_reactive-publish/packages/peerlibrary_reactive-publish.js:283:1)
I20160807-17:59:25.578(8)?     at added (packages/mongo/collection.js:346:11)
I20160807-17:59:25.579(8)?     at packages/mongo/observe_multiplex.js:183:30
I20160807-17:59:25.579(8)?     at Array.forEach (native)
I20160807-17:59:25.580(8)?     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
I20160807-17:59:25.580(8)?     at Object.task (packages/mongo/observe_multiplex.js:177:9)
I20160807-17:59:25.581(8)?     at [object Object]._.extend._run (packages/meteor/fiber_helpers.js:147:1)
I20160807-17:59:25.581(8)?     at packages/meteor/fiber_helpers.js:125:1
