### ISSUE TITLE
Error: Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by Rockettomatoo** [johanbrook/meteor-publication-collector#35]
Hey Johan,

I recently came across a very missleading error from this package

```
Error: Cannot read property 'call' of undefined
    at PublicationCollector.collect (packages/johanbrook:publication-collector/publication-collector.js:67:28)
    ....
```
which refers to those 2 lines:

```js
collect(name, ...args) {
  ...
  
  const handler = Meteor.server.publish_handlers[name];
  const result = handler.call(this, ...args);

  ...
}
```

It turns out I "just" misspelled my publication which apperantly caused the read error.

Due to the thrown error, it took me a little while to figure out what caused the error _(also because I'm not familiar with `publish_handlers` or meteor internals in generall)_. Therefor I would love to get a more specific error message suggesting that I eventually misspelled the publication.

Unfortunately, I'm busy right now and therefor not able to provide a pull request. Sorry!

**Comment by johanbrook** [comment]
Hey!

True, we should totally do a guard check there. Thanks!
