### ISSUE TITLE
Error when object _id is Meteor.Collection.ObjectID

### ISSUE THREAD

**Issue by dai-shi** [johanbrook/meteor-publication-collector#8]
It gives the error:
```
Exception in queued task: Error: Match error: Expected string, got object
```

It's caused by `check(id, String);`. How can this be avoided? Thanks.

**Comment by johanbrook** [comment]
When is this happening?

**Comment by dai-shi** [comment]
When you collect a collection. Something like the followings:
```
const Items = new Mongo.Collection('items');
Items.insert({ _id: new Mongo.ObjectID() });
Meteor.publish('items', () => Items.find({}));
const collector = new PublicationCollector();
collector.collect('items', (collections) => { ... });
```

**Comment by johanbrook** [comment]
Seems you're inserting a document with an `_id` property; is that even possible in Mongo?

**Comment by dai-shi** [comment]
Yeah.
https://docs.mongodb.com/manual/reference/method/db.collection.insert/

**Comment by johanbrook** [comment]
True, I did some testing as well. Changing `check(id, String)` to `check(id, Match.OneOf(String, {_str: String}))` makes sense.

**Comment by dai-shi** [comment]
That would be so great!

**Comment by dai-shi** [comment]
You might want to do:
```
check(id, Match.OneOf(String, Meteor.Collection.ObjectID))
```

**Comment by johanbrook** [comment]
I'm not sure the `{_str: 'longstring'}` will be recognized as an `ObjectID` if it comes straight from the database.

**Comment by johanbrook** [comment]
Nevermind, it worked:

```
> var d = new Mongo.Collection(null);
> d.insert({_id: new Mongo.ObjectID()})
{ _str: '417a3733019e3d7901859d2f' }
> d.findOne()._id
{ _str: '417a3733019e3d7901859d2f' }
> d.findOne()._id instanceof Mongo.ObjectID
true
```

**Comment by dai-shi** [comment]
Awesome. Thanks. @johanbrook
