### ISSUE TITLE
Does not collect results on `ready()`

### ISSUE THREAD

**Issue by drewmoore** [johanbrook/meteor-publication-collector#9]
When a collection is published using the low-level publication API, calling `this.ready()` does not seem to have any effect. My tests are reporting: `Error: timeout of 2000ms exceeded.`. I can't replicate this error when running the app and subscribing to the same publication. I noticed this package's tests are testing publications that all use `return`, so it may be worth checking this use case.

Thanks for the package, though. It makes testing so much easier in the majority of use cases.

**Comment by drewmoore** [comment]
I actually found that the version I was running was 1.01. When I updated to 1.02 this bug disappeared. Thanks!

**Comment by johanbrook** [comment]
Neat!
